import axios from 'axios';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Test the PDF generation endpoint
const testPDFGeneration = async () => {
  try {
    const testContent = `# Test Article

This is a test article generated by AI.

## Introduction

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

## Main Content

* Point 1: Important information
* Point 2: More details
* Point 3: Final thoughts

## Conclusion

This concludes our test article. The PDF generation should work properly with formatted content.`;

    const testTitle = "Test Article PDF";

    console.log('Testing PDF generation endpoint...');
    
    const response = await axios.post('http://localhost:3000/api/ai/generate-article-pdf', 
      {
        content: testContent,
        title: testTitle
      },
      {
        headers: {
          'Content-Type': 'application/json'
        },
        responseType: 'arraybuffer'
      }
    );

    if (response.status === 200) {
      // Save the PDF for verification
      const pdfPath = `${__dirname}/test_output.pdf`;
      fs.writeFileSync(pdfPath, response.data);
      console.log('✅ PDF generated successfully!');
      console.log(`📄 PDF saved to: ${pdfPath}`);
      console.log(`📊 PDF size: ${response.data.length} bytes`);
    } else {
      console.log('❌ Unexpected response status:', response.status);
    }

  } catch (error) {
    if (error.response) {
      console.log('❌ Server responded with error:', error.response.status);
      console.log('Response data:', error.response.data.toString());
    } else if (error.request) {
      console.log('❌ No response received from server');
      console.log('Is the server running on port 3000?');
    } else {
      console.log('❌ Error:', error.message);
    }
  }
};

// Run the test
testPDFGeneration();